# Generated by Django 5.2.1 on 2025-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_post_total_likes_post_social_post_total_l_b22ce0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='قعال'),
        ),
    ]
